AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for the GitHub Serverless application
Resources:
  GitHub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: github-lambda
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          region: us-west-2
      Events:
        GitHubIssues:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *) # Run every 15 minutes, every day
      Tags:
        commit: xxx
      Description: Collecting GitHub issues for the current user
      MemorySize: 128