AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for the GitHub Serverless application
Resources:
  GitHub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: github
      Runtime: go1.x
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
      Events:
        GitHubIssues:
          Type: Schedule
          Properties:
            Schedule: cron(0/15 * * * ? *)
      Environment:
        Variables:
          apptoken: {/github/apptoken}
          interval: {/github/interval}
          trello_arn: {/trello/arn}
      Tags:
        commit: xxx